








post0:
 date: "15 Julho 2019"
 title: "Como nasceu o projeto Entrevista Descomplicada."
 description: "O que nós acreditamos sobre processos seletivos"
 link: "/como-nasceu-o-projeto-entrevista-descomplicada.html"
 category: "Entrevista"
 photo: "https://images.pexels.com/photos/1068523/pexels-photo-1068523.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
 video: "https://www.youtube.com/embed/kOkvLbzp8Ow"
 text:
  "

<p><span style='font-weight: 400;'>O projeto Entrevista Descomplicada nasceu da insatisfa&ccedil;&atilde;o com os processos de sele&ccedil;&atilde;o das grandes empresas. Cada vez mais n&oacute;s (candidatos) estamos mais preparados e ainda assim </span><strong>recebemos um N&Atilde;O em entrevistas sem nenhum tipo de explica&ccedil;&atilde;o</strong><span style='font-weight: 400;'>. Aqui o candidato vai receber informa&ccedil;&otilde;es em detalhe sobre como se preparar e conseguir a t&atilde;o sonhada vaga de trabalho.</span></p>
<p>&nbsp;</p>
<p><span style='font-weight: 400;'>A ideia do projeto &eacute; fornecer dicas simples de como se preparar para os processos seletivos de forma que o candidato consiga se expressar de forma clara, contando todas as suas qualidades, de forma a conseguir a aprova&ccedil;&atilde;o! Neste processo vamos dizer exatamente como &eacute; o processo seletivo, o que os entrevistadores pensam e principalmente, como atravessar todas as 'pegadinhas' que entrevistadores muitas vezes acham necess&aacute;rio colocar na frente do candidato. Vamos dizer a verdade nua e crua do que esperar em uma entrevista e o que fazer para sair com a vaga a m&atilde;o.</span></p>
<p>&nbsp;</p>
<p><span style='font-weight: 400;'>Se inscreva para receber as dicas toda semana por email. Esperamos por voc&ecirc; e sua vaga dos sonhos te espera em breve!! : )</span></p>
<p>&nbsp;</p>
<p><span style='font-weight: 400;'>Veja abaixo o trailer do canal!!!</span></p>


  "
#------------------------------------------------------- END POST -----------------------------------------------------------------------

post1:
 date: "17 Julho 2019"
 title: "Como identificar pontos de melhoria em processos seletivos?"
 description: "Identifique o que você pode menlhorar com essas dicas."
 link: "/como-identificar-pontos-de-melhoria-em-processos-seletivos.html"
 category: "Entrevista"
 photo: "https://images.pexels.com/photos/356043/pexels-photo-356043.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
 video: "https://www.youtube.com/embed/aw6KqlzA53Y"
 text:
  "
  <p><span style='font-weight: 400;'>Voc&ecirc; j&aacute; fez um processo seletivo e depois de muitas etapas simplesmente recebeu um 'sucesso na sua jornada' sem nenhuma explica&ccedil;&atilde;o aparente? N&oacute;s tamb&eacute;m, por isso desenvolvemos esse m&eacute;todo para, pelo menos, tentar rastrear o que pode ter acontecido de forma a melhorar a pr&oacute;xima entrevista.</span></p>
<p>&nbsp;</p>
<p><span style='font-weight: 400;'>No v&iacute;deo a seguir voc&ecirc; vai <strong>conhecer os dois m&eacute;todos.</strong> O primeiro &eacute; bem simples e <strong>requer somente um email</strong>, por&eacute;m muitas vezes n&atilde;o d&aacute; a resposta esperada. <strong>O segundo &eacute; mais trabalhoso mas pelo menos garante que voc&ecirc; est&aacute; no caminho certo</strong>.</span></p>
<p>&nbsp;</p>
<p><span style='font-weight: 400;'>Veja mais sobre como identificar pontos de melhoria em processos seletivos nos v&iacute;deos a seguir:</span></p>


  "
#------------------------------------------------------- END POST -----------------------------------------------------------------------


post2:
 date: "25 Julho 2019"
 title: "Quais os pilares de um bom currículo e porque isso é importante?"
 description: "Saiba quais os pilares de um bom currículo e comunique de forma clara seu potencial"
 link: "/quais-os-pilares-de-um-bom-curriculo.html"
 category: "Currículo"
 photo: "https://images.pexels.com/photos/590016/pexels-photo-590016.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
 video: "https://www.youtube.com/embed/iTe6Ybet0EY"
 text:
  "
 <p><span style='font-weight: 400;'>&Eacute; necess&aacute;rio muita clareza para se comunicar de forma clara as informa&ccedil;&otilde;es de um curr&iacute;culo. A forma mais f&aacute;cil de se conseguir isso &eacute; seguir uma boa estrutura na hora de escrever o CV. </span><strong>Para isso &eacute; preciso conhecer os pilares de uma boa estrutura e como se expressar atrav&eacute;s deles.&nbsp;</strong></p>
<p>&nbsp;</p>
<p><span style='font-weight: 400;'>Nesse v&iacute;deo mostramos os tr&ecirc;s pilares de um bom CV e como isso se traduz na pr&aacute;tica como voc&ecirc; deve montar o seu curr&iacute;culo de forma a expressar todo o seu potencial em uma entrevista.</span></p>
<p>&nbsp;</p>
<p><span style='font-weight: 400;'>Veja em detalhes no pr&oacute;ximo v&iacute;deo:</span></p>


  "
#------------------------------------------------------- END POST -----------------------------------------------------------------------

post3:
 date: "19 Agosto 2019"
 title: "Você sabe quais as perguntas mais comuns em uma entrevista de emprego? Aprenda quais são e como responder cada uma delas!"
 description: "Descubra as perguntas mais recorrentes em toda entrevista e se prepare préviamente."
 link: "/as-5-perguntas-mais-comuns-em-entrevistas.html"
 category: "Currículo"
 photo: "https://images.pexels.com/photos/1226398/pexels-photo-1226398.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
 video: "https://www.youtube.com/embed/9GB2PAZLRWo"
 text:
  "
<p><span style='font-weight: 400;'>Voc&ecirc; sabe quais as perguntas mais comuns em uma entrevista de emprego? Aprenda quais s&atilde;o e como responder cada uma delas!</span></p>
<p><br /><span style='font-weight: 400;'>Saber antecipadamente as perguntas de qualquer situa&ccedil;&atilde;o ajuda a preparar de </span><strong>forma convincente e estruturada</strong><span style='font-weight: 400;'> as respostas. Neste v&iacute;deo vamos explorar as perguntas mais frequentes em uma entrevista assim como poss&iacute;veis respostas pra cada uma delas. O v&iacute;deo &eacute; longo mas sem d&uacute;vida vale a pena assistir at&eacute; o final uma vez que o conte&uacute;do vai, sem d&uacute;vida, </span><strong>te preparar pra uma entrevista melhor!</strong></p>


  "
#------------------------------------------------------- END POST -----------------------------------------------------------------------

post4:
 date: "8 Setembro 2019"
 title: "Como falar sobre qualidades e defeitos em uma entrevista de trabalho"
 description: "Aprenda como falar dos seus pontos positivos e negativos em uma entrevista de trabalho seguindo esse passo a passo."
 link: "/como-falar-sobre-qualidades-e-defeitos-em-uma-entrevista-de-trabalho.html"
 category: "Currículo"
 photo: "https://images.pexels.com/photos/843563/pexels-photo-843563.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
 video: "https://www.youtube.com/embed/cSauwUxCbQ0"
 text:
  "
<p>Descubra como contar seu <strong>pontos fortes</strong> e seus <strong>pontos fracos</strong> durante uma entrevista de emprego com essas dicas!</p>


  "
#------------------------------------------------------- END POST -----------------------------------------------------------------------

post6:
 date: "16 Outubro 2019"
 title: "Como escrever seu currículo sem ter experiências profissionais?"
 description: "Aprenda a escrever seu currículo se você é recém-formado e ainda não possuí experiência profissional relevante."
 link: "/como-escrever-seu-curriculo-sem-ter-experiencias-profissionais.html"
 category: "Currículo"
 photo: "https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
 video: "https://www.youtube.com/embed/l-MgG-lgkTA"
 text:
  "
<p>Descubra como escrever seu currículo se apoaiando em experiências sem carteira assinada. Aproveite as experiências de faculdade para demonstrar suas habilidades profissioanis!</p>


  "
#------------------------------------------------------- END POST -----------------------------------------------------------------------

ultimo:
 date: "29 Outubro 2019"
 title: "Como lidar com exigências absurdas de entrevistas de emprego?"
 description: "Aprenda a lidar com as exigências absurdas das oportunidades profissionais que o mercado exige!"
 link: "/como-lidar-com-exigencias-absurdas-de-entrevistas-de-emprego.html"
 category: "Currículo"
 photo: "https://images.pexels.com/photos/38630/bodybuilder-weight-training-stress-38630.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260"
 video: "https://www.youtube.com/embed/eBJUUPX-Avw"
 text:
  "
<p>Cada vez mais o mercado de trabalho exige habilidades que só o superman tem, no entanto tenha a certeza que todo mundo é, de fato, um ser humano normal. Então qual a diferença entre os que conseguem uma vaga de trabalho pra aqueles que ainda estão procurando uma oportunidade? Veja esse vídeo e descubra!!!</p>


  "
#------------------------------------------------------- END POST -----------------------------------------------------------------------

post7:
 date: "29 Outubro 2019"
 title: "A primeira entrevista de emprego"
 description: "Como foi minha primeira entrevista de emprego?"
 link: "/como-foi-minha-primeira-entrevista-de-emprego.html"
 category: "Entrevista"
 photo: "https://images.pexels.com/photos/3799787/pexels-photo-3799787.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
 video: "https://www.youtube.com/embed/qT1BbQ7SWhM"
 text:
  "

  <p> A primeira entrevista você nunca esquece... Daí nasceu a ideia para a Entrevista Descomplicada :) </p>


  "
#------------------------------------------------------- END POST -----------------------------------------------------------------------



