



vaga0:
 link: "/vaga-598.html"
 logo: "https://1000logos.net/wp-content/uploads/2017/10/Logo-Nestle-png.jpg"
 data_inicio: "31/03/2020"
 data_fim: "31/12/2021"
 empresa: "Nestlé"
 titulo: "Nestlé - Programa de Estágio"
 site: "https://www.atsglobe.com/hotsite/estagionestle"
 tipo: "Estágio"
 descricao_curta: "Programa de estágio"
 descricao_completa:
  "
Você sabia que o Programa de Estágio na Nestlé é contínuo?

E o que isso quer dizer? Quer dizer que o nosso Programa funciona durante o ano todo, ou seja:

Você permanece ativo em nosso banco, até que tenha pelo menos 1 ano para concluir o seu curso;

A gente pode entrar em contato com você a qualquer momento, para diferentes formatos de avaliação;

Uma vez que você é entrevistado, sua avaliação fica em nosso sistema e podemos entrar em contato para diferentes vagas (claro, a gente faz essa escolha juntxs, tá?)
Tem uma coisa super importante, viu? As vagas são para trabalhar em São Paulo e para início imediato.

Quer um mundo de possibilidades pra você inovar e descobrir o que mais gosta de fazer? Então vem com a gente.
  "
#------------------------------------------------------- END POST -----------------------------------------------------------------------


vaga1:
 link: "/vaga-333.html"
 logo: "https://media-exp1.licdn.com/dms/image/C560BAQEAxZNN_DbjsQ/company-logo_200_200/0?e=2159024400&v=beta&t=b81hHiXUwwZ_QH3GwYKJ7wjwo_o3u4MBBrmvY4ztpBE"
 data_inicio: "Vagas abertas"
 data_fim: "-"
 empresa: "Furukawa Eletric"
 titulo: "Trainee Furukawa 2020"
 site: "https://www.atsglobe.com/hotsite/traineefurukawa2020"
 tipo: "Trainee"
 descricao_curta: "Programa Trainee Furukawa"
 descricao_completa:
  "
O Programa de Trainee Furukawa 2020 busca rejuvenescer a empresa, atraindo jovens profissionais de alto potencial com foco no desenvolvimento humano e social.

Os Trainees passarão por uma imersão completa na nossa cultura por 12 meses, em uma jornada por todas as áreas da empresa realizando projetos desafiadores e relevantes.

Saiba mais: https://www.youtube.com/watch?v=_PdYiBdj6Qk

Inscreva-se no nosso programa e fique atento(a) às fases e convocações.

Boa sorte!
  "
#------------------------------------------------------- END POST -----------------------------------------------------------------------

vaga2:
 link: "/vaga-294.html"
 logo: "https://1000logos.net/wp-content/uploads/2017/04/PG-Logo-500x280.png"
 data_inicio: "Vagas abertas"
 data_fim: "-"
 empresa: "Procter & gamble"
 titulo: "P&G - Programa de Estágio"
 site: "https://www.pgcareers.com/job/salvador/management-internship-in-sales-salvador-e-belo-horizonte/936/14742120?src=JB-15138&utm_source=site&utm_medium=CT"
 tipo: "Estágio"
 descricao_curta: "Programa de estágio"
 descricao_completa:
  "
 Do you want to be in the driving seat, selling our global leading brands? Are you intrigued by the idea of building long-term business relationships with our customers? To develop and negotiate plans which create a benefit for our shoppers, our customers and our Company? Then an Internship in our Strategic Sales department is the right place for you. We are here to help you gain a magical experience. We have internship assignments in the areas of Key account management, Shopper Based Design, Category management & Business Analysis.
  "
#------------------------------------------------------- END POST -----------------------------------------------------------------------

vaga3:
 link: "/vaga-128.html"
 logo: "https://empretsinf.blogs.upv.es/files/2013/06/logo-ms1.png"
 data_inicio: "-"
 data_fim: "08/06/2020"
 empresa: "MANAGEMENT SOLUTIONS"
 titulo: "Consultor de Negócios"
 site: "http://www.managementsolutions.com"
 tipo: "Consultor de Negócios"
 descricao_curta: "Vaga para consultor de negócios"
 descricao_completa:
  "
A Management Solutions é uma firma internacional de consultoria, que tem como foco a assessoria de negócio, riscos, finanças, organização e processos, tanto nos seus componentes funcionais, como na implantação de tecnologias relacionadas. Contamos atualmente com uma equipe multidisciplinar (funcionais, matemáticos, técnicos e de integração de sistemas) de 2.500 profissionais.
- A Management Solutions desenvolve a sua atividade através de 30 escritórios, 14 na Europa, 15 nas Américas e 1 na Ásia, a partir dos quais atende de forma recorrente clientes que atuam em mais de 40 países em quatro grandes áreas geográficas (Europa, Américas, Ásia e África).
- Envie seu currículo para recursos.humanos@msbrazil.com
  "
#------------------------------------------------------- END POST -----------------------------------------------------------------------

vaga4:
 link: "/vaga-403.html"
 logo: "https://lever-client-logos.s3.amazonaws.com/Amaro_logo.png"
 data_inicio: "-"
 data_fim: "11/06/2020"
 empresa: "Amaro"
 titulo: "Performance Marketing Analyst"
 site: "https://jobs.lever.co/amaro/fb86887b-e802-497a-a9a0-8a5fccc2a779"
 tipo: "Analista"
 descricao_curta: "Performance Marketing Analyst"
 descricao_completa:
  "
AMARO is a technology company and digitally native fashion brand that innovates how people discover, buy and wear fashion. Headquartered in São Paulo, our mission is to make it easy and delightful for all digitally minded consumers to find products that fit their lives and values.

Born in Brazil with global ambition, we design for how we believe the world should be, not what it is today. We are always growing together with our teams. It takes a more honest, accessible and clever approach to build our products and our customer experience. We are committed to understanding people's lives. It's in our DNA!

AMARO is seeking a Performance Marketing Analyst to support our paid media squad and scale customer acquisition efforts. You’ll be joining the chapter focused on performance marketing campaigns, media optimization and driving company growth.

You seek to have a significant impact and ownership of a significant marketing budget at a workplace that values taking controlled risks and collaborative work.
What you'll do:
Become an expert in performance media channels, specially Google and Facebook;
Learn how to create, launch and optimize campaigns across different online media channels;
Support the creation and automation of reports to help the Paid Media Squad make better decisions;
Be in constant contact with our Google and Facebook account managers, always staying on top of social media activities, industry trends, digital marketing events and new technologies in order to bring new insights.
What your qualifications are:
Bachelors degree in a STEM field, Engineering, Economics, Biz Admin from a top university;
You are a digitally native person who can quickly adopt new tools and technologies;
You’re fluent or have an advanced level of English.
  "
#------------------------------------------------------- END POST -----------------------------------------------------------------------

vaga5:
 link: "/vaga-733.html"
 logo: "https://media-exp1.licdn.com/dms/image/C4E0BAQEXCFanTSDLyA/company-logo_200_200/0?e=2159024400&v=beta&t=SPIrJgo3Mi6wQAwymAYKhnRSY4S7MaB_bnDsVOWCeQw"
 data_inicio: "Imediato"
 data_fim: "-"
 empresa: "Bureau Works"
 titulo: "GERENTE DE ESTRATÉGIA DE MERCADO"
 site: "https://www.linkedin.com/jobs/view/1846594650/"
 tipo: "Gerente"
 descricao_curta: "Gerente de Estratégia"
 descricao_completa:
  "
Bureau Works is a platform for orchestrating content delivery globally. By unifying all content streams, whether via API integrations or by capturing emailed files, Bureau Works enables comprehensive oversight of translation and localization operations. Using our innovative tools, you can setup reliable and automated workflows, streamline in-country review, and use rich quality data to proactively manage quality.

Principais Atribuições do Cargo - Work independently - make decisions and ensure decision-making path is followed - Problem solver - present and introduce solutions - Analytical prowess - common sense, self-criticism, self-awareness - Flexibility - quickly adjust to changes needed to role and expectations in a start-up environment - Systems architecture - understand how systems operate at a fundamental level - Results-driven - transform the organization as necessary in order to reach desired results - Read between the lines - great at communicating with stakeholders across the globe from all kinds of industries and levels - Not looking for a traditional desk job - looking to become an agent of change

"
#------------------------------------------------------- END POST -----------------------------------------------------------------------




